### ISSUE TITLE
https://fb2ical.com not working

### ISSUE THREAD

**Issue by rebelcode-xr** [comatory/fb2iCal#2]
Hi, thanks for your amazing piece of code 🥳 

Sadly the online instance https://fb2ical.com doesn't work anymore 😭

**Comment by comatory** [comment]
@rebelcode-xr Hi thanks for appreciating the work. Yes I noticed my server wasn't receiving connections, should be fixed now.

I will look into more robust solution for this instance.

**Comment by comatory** [comment]
@rebelcode-xr I am hosting the app on Firebase now so the uptime should not be an issue anymore. 
I retained the ability to host the app on regular server as well so simple web server with NodeJS will still work.

**Comment by rebelcode-xr** [comment]
Awesome! :D
